apps/api/urls.py
# @Author  : cheertt
# @Time    : 2019/3/6 8:46
# @Remark  : api界面的相关url链接
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from api import views_member, views_credit
from api import views_commodity
from api import views_recommendations
from api import views_hotcommend
urlpatterns = [
    # 会员信息增改删查操作
    url(r'^member/$', views_member.MemberView.as_view(), name="member"),
    url(r'^member/savepic', views_member.MemberUploadFace.as_view(), name="member-save-face"),
    url(r'^member/login', csrf_exempt(views_member.MemberLoginView.as_view()), name="member-login"),
    url(r'^member/checkreg', csrf_exempt(views_member.MemberCheckRegView.as_view()), name="member-checkreg"),
    url(r'^member/info', views_member.MemberInfoView.as_view(), name="member-info"),
    url(r'^member/order', views_member.MemberOrderView.as_view(), name='member-order'),
    url(r'^member/credit_list', views_credit.CreditListView.as_view(), name='credit-list'),
    url(r'^member/credit_share', csrf_exempt(views_credit.ShareView.as_view()), name='credit-share'),

    url(r'^commodity/comment_add', views_commodity.CommentAddView.as_view(), name='comment-add'),
    url(r'^commodity/search', views_commodity.CommoditySearchView.as_view(), name="commodity-search"),
    url(r'^commodity/commodity_type', views_commodity.CommodityTypeView.as_view(), name="commodity-type"),
    url(r'^commodity/commodity_list', views_commodity.CommodityListView.as_view(), name="commodity-list"),
    url(r'^commodity/commodity_info', views_commodity.CommodityInfoView.as_view(), name="commodity-info"),
    url(r'^commodity/commodity_comments', views_commodity.CommodityCommentsView.as_view(), name="commodity-comments"),
    url(r'^commodity/cart_add', views_commodity.CartAddView.as_view(), name="cart-add"),
    url(r'^commodity/cart_list', views_commodity.CartListView.as_view(), name="cart-list"),
    url(r'^commodity/cart_del', csrf_exempt(views_commodity.CartDeltView.as_view()), name="cart-del"),

    url(r'^recommendations/toprecommendations', csrf_exempt(views_recommendations.TopRecommendationsView.as_view()), name="TopRecommendations"),
    url(r'^recommendations/allrecommendations', csrf_exempt(views_recommendations.AllRecommendationsView.as_view()),
        name="AllRecommendations"),
    url(r'^recommendations/commonrecommendations',csrf_exempt(views_recommendations.Get_Common_Recommenadations.as_view()), name="CommonRecommendations"),
    url(r'^hotcommend/hot_commodity', views_hotcommend.HotCommodityView.as_view(), name="hot-commodity"),


]

apps/commodity/urls.py
from django.conf.urls import url

from commodity import views

urlpatterns = [

    url(r'commodity/$', views.CommodityView.as_view(), name='commodity'),
    url(r'^commodity/list$', views.CommodityListView.as_view(), name="commodity-list"),
    url(r'^commodity/create$', views.CommodityCreateView.as_view(), name="create"),
    url(r'^commodity/update$', views.CommodityUpdateView.as_view(), name="update"),
    url(r'^commodity/delete$', views.CommodityDeleteView.as_view(), name='delete'),
    url(r'^commodity/enable$', views.CommodityEnableView.as_view(), name='enable'),
    url(r'^commodity/disable$', views.CommodityDisableView.as_view(), name='disable'),
    url(r'^commodity/detail$', views.CommodityDetailView.as_view(), name="detail"),
    url(r'^commodity/uploadimage$', views.UploadImageView.as_view(), name="commodity-uploadimage"),
]

apps/hotcommend/urls.py
# @Time    : ${3/10/2019} ${TIME}
# @Author  : $Sutrue
# @Remark  :
from django.conf.urls import url
from hotcommend import views

urlpatterns = [

    url(r'hotcommend/$', views.CommendView.as_view(), name='hotcommend'),
    url(r'^hotcommend/item_rank$', views.ItemRank.as_view(), name='item_rank'),
    url(r'^hotcommend/add_commendation$', views.AddCommendation.as_view(), name='add_commendation'),
    url(r'^hotcommend/hot_list$', views.HotAdd.as_view(), name='hot_add'),
    url(r'hotcommend/to_hot_list', views.ToTheList.as_view(), name='to_hot_list'),
    url(r'^hotcommend/hot_delete', views.HotDeleteView.as_view(), name='hot_delete'),

    # url(r'^hotcommend/item_rank', views.ChooseDays.as_view(), name='choose_days'),
    # url(r'^hotcommend/item_rank/$', views.SalesQuery.as_view(), name='sales_query'),
]

reporjectred/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from reporjectred.settings import MEDIA_ROOT
from users.views import IndexView, LoginView, LogoutView
from personal.views import PersonalView, UserInfoView, UploadImageView, \
    PasswdChangeView
from api.views_member import FaceView


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^$', IndexView.as_view(), name='index'),
    # 用户登录
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),

    url(r'^personal/$', PersonalView.as_view(), name="personal"),
    url(r'^personal/userinfo', UserInfoView.as_view(), name="personal-user_info"),
    url(r'^personal/uploadimage', UploadImageView.as_view(), name="personal-uploadimage"),
    url(r'^personal/passwordchange', PasswdChangeView.as_view(), name="personal-passwordchange"),

    url(r'^users/', include('users.urls', namespace='users')),

    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^commodity/', include('commodity.urls', namespace='commodity')),

    url(r'^recommendations/', include('recommendations.urls', namespace='recommendations')),
    url(r'^comment/', include('apps.comment.urls', namespace='comment')),

    url(r'^hotcommend/', include('hotcommend.urls', namespace='hotcommend')),

    url(r'^api/face/$', FaceView.as_view(), name="face"),

    url(r'^api/', include('api.urls', namespace='api')),
]

apps/hotcommend/models.py
# @Time    : ${3/10/2019} ${TIME}
# @Author  : $Sutrue
# @Remark  :

from django.db import models

# Create your models here.

# class Commendation(models.Model):
#     assin = models.CharField(max_length=100, blank=False, null=False)
#     title = models.CharField(max_length=200, blank=True, null=True)
#     type = models.CharField(max_length=20, blank=True, null=True)
#
#     class Meta:
#         db_table = 'commendation'


class hot_list(models.Model):
    """
    热销表单model
    """
    assin = models.CharField(max_length=200, blank=False, null=False)
    title = models.CharField(max_length=200, blank=True, null=True)
    categories = models.CharField(max_length=20, blank=True, null=True)
    sales_count = models.CharField(max_length=100, blank=True, null=True)
    present_price = models.CharField(max_length=200, blank=True, null=True)
    imUrl = models.CharField(max_length=1000, blank=True, null=True)

    class Meta:
        """
        指定该类的数据库表单名字
        """
        db_table = 'hot_list'

class transaction_record(models.Model):
    """
    交易记录model
    """
    # id = models.IntegerField()
    user_id = models.CharField(max_length=255, blank=False, null=False)
    assin = models.CharField(max_length=255, blank=False, null=False)
    rating = models.CharField(max_length=100, blank=True, null=True)
    date = models.DateTimeField(max_length=255, blank=False, null=False)

    class Meta:
        """
        指定该类的数据库表单名字
        """
        db_table = 'transaction_record'

apps/hotcommend/views.py
# @Time    : ${3/10/2019} ${TIME}
# @Author  : $Sutrue
# @Remark  : 视图函数
import json
from datetime import datetime, timedelta
from django.shortcuts import render

from django.shortcuts import HttpResponse
from django.views.generic.base import View
from django.core.serializers.json import DjangoJSONEncoder

from django.db.models import Count, Sum, F
from django.utils.safestring import mark_safe
from utils.mixin_utils import LoginRequiredMixin

from commodity.models import Commodity
from order.models import Transaction
from hotcommend.models import hot_list, transaction_record


class CommendView(LoginRequiredMixin, View):
    """
    转入热门推荐页
    """
    def get(self, request):
        """
        向前台发送增速最快的商品的信息
        :param request:
        :return:
        """
        now_time = datetime.now().strftime('%Y-%m-%d')
        # day_7_ago = (datetime.now() + timedelta(days=-7)).strftime('%Y-%m-%d')
        # day_14_ago = (datetime.now() + timedelta(days=-14)).strftime('%Y-%m-%d')
        # day_30_ago = (datetime.now() + timedelta(days=-30)).strftime('%Y-%m-%d')
        day_90_ago = (datetime.now() + timedelta(days=-90)).strftime('%Y-%m-%d')
        ret = dict()

        #最近一周的销量
        recent7 = transaction_record.objects.all().values('assin').\
            annotate(sales_count=Count('id')).\
            filter(date__gte='2013-02-26', date__lte='2013-03-11').order_by('date')
        recent14 = transaction_record.objects.all().values('assin').\
            annotate(sales_count=Count('id')).\
            filter(date__gte='2013-02-11', date__lte='2013-03-11').order_by('date')

        inc = {}
        for i in recent7:
            for j in recent14:
                if j['assin'] == i['assin']:
                    try:
                        inc[i['assin']] = i['sales_count'] / (j['sales_count'] - i['sales_count'])
                    except ZeroDivisionError:
                        pass
                    break

        sort_inc = sorted(inc, key=lambda x: inc[x], reverse=True)[:6]


        data = []
        # 根据日期进行循环
        begin = datetime.strptime("2013-02-11", "%Y-%m-%d")
        end = datetime.strptime("2013-03-11", "%Y-%m-%d")
        delta = timedelta(days=1)

        for assin in sort_inc:
            data_sales = list(transaction_record.objects.all().filter(assin=assin).values('date').
                              annotate(sales_count=Count('id')).
                              filter(date__gte='2013-02-11', date__lte='2013-03-11'))
            has_date = []
            #去除日期的时分秒
            for i in data_sales:
                short = i['date'][:10]
                has_date.append(short)
                i['date'] = short

            #将没有销量的日期销量数定位0
            tmp_d = begin
            while tmp_d <= end:
                str_da = str(tmp_d.strftime("%Y-%m-%d"))
                if str_da not in has_date:
                    data_sales.append({'date': str_da, 'sales_count':0})
                tmp_d += delta


            data_sales = sorted(data_sales, key=lambda x: x['date'])
            data.append([assin, data_sales])
        ret['rates'] = mark_safe(data)

        season_sale = list(Transaction.objects.all().values('commodity', 'commodity__title',
                                                            'commodity__assin').annotate(counts=Sum('num')).
                           filter(joined_date__gte=day_90_ago, joined_date__lte=now_time).order_by('-counts')[:10])
        ret['season'] = mark_safe(season_sale)

        return render(request, 'hotcommend/hot_list.html', ret)


#通过QuerySet的values方法来获取指定字段列的数据内容，转换QuerySet类型最终序列化成json串，返回数据访问接口
class ItemRank(LoginRequiredMixin, View):
    """
    统计最近一个月商品销量
    """
    def get(self, request):
        """
        按商品id统计指定时间内的商品销量，默认近7天的
        """

        now_time = datetime.now().strftime('%Y-%m-%d')
        # day_3_ago = (datetime.now() + timedelta(days=-3)).strftime('%Y-%m-%d')
        # day_7_ago = (datetime.now() + timedelta(days=-7)).strftime('%Y-%m-%d')
        day_30_ago = (datetime.now() + timedelta(days=-30)).strftime('%Y-%m-%d')

        # choose_date = {'3': day_3_ago, '7': day_7_ago, '30': day_30_ago}

        #接收根据assin查询传来的assin值
        if 'assin' in request.GET and request.GET['assin']:
            ret = Commodity.objects.filter(assin=request.GET['assin']).\
                annotate(commodity=F('id'), commodity__title=F('title')).\
                values('commodity', 'commodity__title', 'status')


            status = '0'
            try:
                status = ret.values('status')[0]['status']
            except IndexError:
                pass

            #判断商品是否下架
            if status == '1':
                sales_count = Transaction.objects.all().\
                    filter(commodity__assin=request.GET['assin']).\
                    values('commodity__assin').annotate(sales_count=Sum('num')).\
                    filter(joined_date__gte=day_30_ago, joined_date__lte=now_time)
                count = 0
                try:
                    for item in sales_count:
                        count += item['sales_count']
                except IndexError:
                    count = 0
                    print("无销售记录")

                for item in ret:
                    # a = Commodity.objects.filter(assin=item['assin'])
                    item['sales_count'] = count
                ret = dict(data=list(ret))
                ret = json.dumps(ret, cls=DjangoJSONEncoder)
                return HttpResponse(ret, content_type='application/json')
            else:
                print("不存在")
                ret = dict()
                ret = json.dumps(ret, cls=DjangoJSONEncoder)
                return HttpResponse(ret, content_type='application/json')

        ret = Transaction.objects.all().values('commodity', 'commodity__title').\
        annotate(sales_count=Sum('num')).\
        filter(joined_date__gte=day_30_ago, joined_date__lte=now_time).\
        order_by('-sales_count')[:50]

        # 为每个物品添加对应的title
        # for item in ret:
        #     a = Commodity.objects.filter(assin=item['assin'])
        #     # item['title'] = item['commodity'].
        #     try:
        #         item['title'] = a.values('title')[0]['title']
        #     except IndexError:
        #         print("don't found: ", item['assin'])

        ret = dict(data=list(ret))
        ret = json.dumps(ret, cls=DjangoJSONEncoder)
        return HttpResponse(ret, content_type='application/json')


class AddCommendation(LoginRequiredMixin, View):
    """
    进入热门推荐增加页面
    """
    def get(self, request):
        """
        转入排名页
        :param request:
        :return:
        """
        return render(request, 'hotcommend/item_rank.html')


class HotAdd(LoginRequiredMixin, View):
    """
    显示热门推荐列表
    """
    def get(self, request):
        """
        从后端获得hot_list表的商品
        :param request:
        :return:
        """
        fields = ['assin', 'title', 'sales_count', 'categories', 'id']
        filters = dict()
        if 'assin' in request.GET and request.GET['assin']:
            filters['assin__icontains'] = request.GET['assin']
        if 'title' in request.GET and request.GET['title']:
            filters['title__icontains'] = request.GET['title']
        if 'sales_count' in request.GET and request.GET['sales_count']:
            filters['sales_count'] = request.GET['sales_count']
        if 'categories' in request.GET and request.GET['categories']:
            filters['categories'] = request.GET['categories']
        if 'id' in request.GET and request.GET['id']:
            filters['id'] = request.GET['id']


        #将昨天销量前10的自动加入hot_list表中
        now_time = datetime.now().strftime('%Y-%m-%d')
        yesterday = (datetime.now() + timedelta(days=-1)).strftime('%Y-%m-%d')
        yesterday_count = Transaction.objects.all().values('commodity', 'commodity__assin').\
        annotate(counts=Sum('num')).filter(joined_date__gte=yesterday, joined_date__lte=now_time)[:10]
        for item in yesterday_count:
            if hot_list.objects.filter(assin=item['commodity__assin']).count() == 0:
                temp_b = Commodity.objects.filter(assin=item['commodity__assin']).\
                    values('id', 'assin', 'title', 'categories', 'present_price', 'imUrl')

                hot_commodity = hot_list(assin=temp_b.values('assin')[0]['assin'],
                                         title=temp_b.values('title')[0]['title'],
                                         categories=temp_b.values('categories')[0]['categories'],
                                         imUrl=temp_b.values('imUrl')[0]['imUrl'],
                                         present_price=temp_b.values('present_price')[0]['present_price'],
                                         sales_count=item['counts'], id=temp_b.values('id')[0]['id'])
                hot_commodity.save()

        ret = dict(data=list(hot_list.objects.filter(**filters).values(*fields)))
        ret = json.dumps(ret, cls=DjangoJSONEncoder)

        return HttpResponse(ret, content_type='application/json')


class ToTheList(LoginRequiredMixin, View):
    """
    将选择的商品加入热门商品数据库
    """
    def post(self, request):
        """
        接收前端选择的商品的commodity
        :param request:
        :return:
        """
        ret = dict()
        now_time = datetime.now().strftime('%Y-%m-%d')
        day_30_ago = (datetime.now() + timedelta(days=-30)).strftime('%Y-%m-%d')
        fields = ['id', 'assin', 'title', 'categories', 'present_price', 'imUrl', 'status']

        #销量单独获取
        sales_count = Transaction.objects.all().filter(commodity=request.POST['commodity']).\
            values('commodity').annotate(sales_count=Sum('num')).\
            filter(joined_date__gte=day_30_ago, joined_date__lte=now_time)
        count = 0
        try:
            for item in sales_count:
                count += item['sales_count']
        except IndexError:
            count = 0

templates/hotcommend/hotcommend.html
{% extends "base-left.html" %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.min.css' %}">
<link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
<link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
<!-- iCheck for checkboxes and radio inputs -->
{% endblock %}

{% block content %}

    <!-- Main content -->
    <section class="content-header margin-bottom">
        <ol class="breadcrumb">
            <li><i class=""></i>推荐列表</li>
        </ol>
    </section>
  <section class="content">
                <table id="dtbList" class="display" cellspacing="0" width="100%">
                    <thead>
                    <tr valign="middle">
                        <th><input type="checkbox" id="checkAll"></th>
                        <th>商品ID</th>
                        <th>商品名称</th>
                        <th>商品类别</th>
{#                        <th>品牌</th>#}
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

              <div class="box-header" align="center">
                <div class="btn-group">
                    <button type="button" id="btnCreate" class="btn btn-primary">
                        <i class="glyphicon glyphicon-plus"></i>推荐
                    </button>
                </div>
                <div class="btn-group">
                    <button type="button" id="btnDelete" class="btn btn-danger">
                        <i class="glyphicon glyphicon-trash"></i>撤下
                    </button>
                </div>
              </div>

  </section>

    <!-- /.content -->

{% endblock %}

{% block javascripts %}
  <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'plugins/datatables/dataTables.const.js' %}"></script>
  <script src="{% static 'plugins/datatables/moment.min.js' %}"></script>
  <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
  <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
  <!-- iCheck 1.0.1 -->
  <script type="text/javascript">
	$(function() {
	    $('#COOMDITY-LIST').addClass('active');

	});
  </script>

    <script type="text/javascript">
var oDataTable=null;
$(function() {
	oDataTable = initTable();
	function initTable() {
		var oTable=$('#dtbList').DataTable($.extend(true,{},
						DATATABLES_CONSTANT.DATA_TABLES.DEFAULT_OPTION,
						{
							ajax : {
								"url":"{% url 'commodity:commodity-list' %}",
								"data":function ( d ) {
									d.select=$("#select").val();
								}
						},

						columns : [
								DATATABLES_CONSTANT.DATA_TABLES.COLUMN.CHECKBOX,

								{
									data : "assin",
								},

                                {
									data : "title",
								},

                                {
									data : "categories__type_name",
								},

								{
									{#data : "id",#}
									{#width : "10%",#}
									bSortable : "false",
									render : function(data, type, row, meta) {
										var ret="<button title='删除' onclick='doDelete("
                                            + data + ")'><i class='glyphicon glyphicon-trash'></i></button>";
										return ret;
									}
								} ],
						}));
		return oTable;
	}

   //刷新页面GET查询请求
    $("#btnCommoditySearch").click(function(){
            alert(oDataTable.ajax.all())
            oDataTable.ajax.reload();
        });


	//select选择后刷新页面GET请求
    $("#select").change(function(){
		alert($("#select").val())
		oDataTable.ajax.reload();
	});
	//checkbox全选
    $("#checkAll").on("click", function () {
        if ($(this).prop("checked") === true) {
            $("input[name='checkList']").prop("checked", $(this).prop("checked"));
            $('#example tbody tr').addClass('selected');
        } else {
            $("input[name='checkList']").prop("checked", false);
            $('#example tbody tr').removeClass('selected');
        }
    });


	$("#btnCreate").click(function() {
		var div=layer.open({
			type : 2,
			title : '推荐选择',
			shadeClose : false,
			maxmin : true,
			area : [ '800px', '580px' ],
			content : "{% url 'hotcommend:add_commendation' %}",
			end : function() {
				//关闭时做的事情
				window.location.reload();
			}
		});
           layer.full(div)
	});


	//批量删除
	$("#btnDelete").click(function() {
		if ($("input[name='checkList']:checked").length == 0){
			layer.msg("请选择要删除的记录");
			return ;
		}

		var arrId= new Array();
		$("input[name='checkList']:checked").each(function(){
			//alert($(this).val());
			arrId.push($(this).val());
		});

		sId=arrId.join(',');

		layer.alert('确定删除吗？', {
			title:'提示'
			,icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
			,time: 0 //不自动关闭
			,btn: ['YES', 'NO']
			,yes: function(index){
			 	layer.close(index);
			 	$.ajax({
					type: "POST",
					url : "{% url 'commodity:delete' %}",
					data : {"id":sId, csrfmiddlewaretoken: '{{ csrf_token }}'},
					cache: false,
					success : function(msg) {
						if (msg.result){
							layer.alert("操作成功",{icon:1});
							oDataTable.ajax.reload();
						}else{
							//alert(msg.message);
							layer.alert("操作失败",{icon:2});
						}
						return ;
					}
				});
			}
		});
	});


});

function doDetail(id){
    window.location.href="{% url 'commodity:detail' %}?id="+id;
}

function doUpdate(id){
	var div=layer.open({
		type : 2,
		title : '修改商品信息',
		shadeClose : false,
    	maxmin : true,
		area : [ '800px', '580px' ],
		content : "{% url 'commodity:update' %}"+'?id='+id,
		end : function() {
			//oDataTable.ajax.reload();
            window.location.reload();

		}
	});
	layer.full(div)
}

//删除单个数据
function doDelete(id){
    layer.alert('确定删除吗？', {
        title:'提示'
        ,icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
        ,time: 0 //不自动关闭
        ,btn: ['YES', 'NO']
        ,yes: function(index){
            layer.close(index);
            $.ajax({
                type: "POST",
                url : "{% url 'commodity:delete' %}",
                data : {"id":id, csrfmiddlewaretoken: '{{ csrf_token }}'},  //防止post数据时报 csrf_token 403
                cache: false,
                success : function(msg) {
                    if (msg.result){
                        layer.alert('删除成功',{icon: 1});
                        oDataTable.ajax.reload();
                    }else{
                        //alert(msg.message);
                        layer.alert('删除失败', {icon: 2});
                    }
                    return ;
                }
            });
        }
    });

}
</script>
<script>
  $(function () {
    //Initialize Select2 Elements
    $(".select2").select2();
  });
</script>
{% endblock %}