apps/commodity/urls.py
from django.conf.urls import url

from commodity import views

urlpatterns = [

    url(r'commodity/$', views.CommodityView.as_view(), name='commodity'),
    url(r'^commodity/list$', views.CommodityListView.as_view(), name="commodity-list"),
    url(r'^commodity/create$', views.CommodityCreateView.as_view(), name="create"),
    url(r'^commodity/update$', views.CommodityUpdateView.as_view(), name="update"),
    url(r'^commodity/delete$', views.CommodityDeleteView.as_view(), name='delete'),
    url(r'^commodity/enable$', views.CommodityEnableView.as_view(), name='enable'),
    url(r'^commodity/disable$', views.CommodityDisableView.as_view(), name='disable'),
    url(r'^commodity/detail$', views.CommodityDetailView.as_view(), name="detail"),
    url(r'^commodity/uploadimage$', views.UploadImageView.as_view(), name="commodity-uploadimage"),
]

apps/recommendations/urls.py
# @Time    : 2019/3/6 20:00
# @Author  : Virus
# @Remark  :


from django.conf.urls import url

from recommendations import views

urlpatterns = [
    url(r'recommendations/$', views.RecommendationsView.as_view(), name="recommendations"),
    url(r'^recommendations/list$', views.RecommendationsListView.as_view(), name="recommendations-list"),
    url(r'^recommendations/detail$', views.RecommendationsDetailView.as_view(), name="detail"),]
    # url(r'^user/detail$', views_user.UserDetailView.as_view(), name="user-detail"),
    # url(r'^user/update$', views_user.UserUpdataView.as_view(), name="user-update"),
    # url(r'^user/create$', views_user.UserCreateView.as_view(), name="user-create"),
    # url(r'^user/delete$', views_user.UserDeleteView.as_view(), name="user-delete"),
    # url(r'^user/enable$', views_user.UserEnableView.as_view(), name="user-enable"),
    # url(r'^user/disable$', views_user.UserDisableView.as_view(), name="user-disable"),
    # url(r'^user/adminpasswdchange$', views_user.AdminPasswdChangeView.as_view(), name="user-adminpasswdchange"),

reporjectred/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from reporjectred.settings import MEDIA_ROOT
from users.views import IndexView, LoginView, LogoutView
from personal.views import PersonalView, UserInfoView, UploadImageView, \
    PasswdChangeView
from api.views_member import FaceView


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^$', IndexView.as_view(), name='index'),
    # 用户登录
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),

    url(r'^personal/$', PersonalView.as_view(), name="personal"),
    url(r'^personal/userinfo', UserInfoView.as_view(), name="personal-user_info"),
    url(r'^personal/uploadimage', UploadImageView.as_view(), name="personal-uploadimage"),
    url(r'^personal/passwordchange', PasswdChangeView.as_view(), name="personal-passwordchange"),

    url(r'^users/', include('users.urls', namespace='users')),

    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^commodity/', include('commodity.urls', namespace='commodity')),

    url(r'^recommendations/', include('recommendations.urls', namespace='recommendations')),
    url(r'^comment/', include('apps.comment.urls', namespace='comment')),

    url(r'^hotcommend/', include('hotcommend.urls', namespace='hotcommend')),

    url(r'^api/face/$', FaceView.as_view(), name="face"),

    url(r'^api/', include('api.urls', namespace='api')),
]

apps/commodity/models.py
# @Time    : 2019年3月5日19:54:50
# @Author  : xie Liangcai
# @Remark  : 商品种类，信息，价格model


from django.db import models
import django.utils.timezone as timezone


# 商品类别表
class CommodityType(models.Model):
    '''
    商品类型model
    '''
    type_name = models.CharField(max_length=1000)
    description = models.CharField(max_length=1000, blank=True, null=True)

    class Meta:
        db_table = "commodity_type"


# 商品列表
class Commodity(models.Model):
    '''
       商品信息model
    '''
    commodity_status = (
        ("0", "下架"),
        ("1", "在售"),
    )
    assin = models.CharField(max_length=100, blank=False, null=False)
    categories = models.ForeignKey(CommodityType, on_delete=models.SET_NULL, blank=True, null=True)
    present_price = models.FloatField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    title = models.CharField(max_length=1000, blank=True, null=True)
    # imUrl = models.ImageField(upload_to="commImage",default="commImage/default.jpg")
    imUrl = models.CharField(max_length=1000, blank=True, null=True)
    brand = models.CharField(max_length=1000, blank=True, null=True)
    buyDate = models.DateTimeField('商品购买日期', blank=True, null=True, default=timezone.now)
    warrantyDate = models.DateTimeField('商品保质日期', blank=True, null=True, default=timezone.now)
    status = models.CharField(choices=commodity_status, max_length=20, default="1", verbose_name="商品的状态")

    def short_description(self):
        if len(str(self.description)) > 400:
            return '{}...'.format(str(self.description)[0:400])
        else:
            return str(self.description)

    def short_title(self):

        if len(str(self.title)) > 50:
            return '{}...'.format(str(self.title)[0:50])
        else:
            return str(self.title)

    class Meta:
        db_table = "commodity"


# 商品价格表
class Commodity_price(models.Model):
    '''
       商品价格model
    '''
    asin = models.ForeignKey(Commodity)
    price = models.FloatField(default=0, blank=True)
    updataTime = models.DateTimeField('价格更新日期', auto_now_add=True)
    description = models.CharField(max_length=1000, blank=True, null=True)

    class Meta:
        db_table = "commodity_price"

apps/recommendations/models.py
# @Time    : 2019/3/6 20:00
# @Author  : Virus
# @Remark  :




from django.db import models

# Create your models here.
class Users_Recommendations(models.Model):
    """
    与User_Recommendations表中的字段相对应，
    """
    user_id = models.CharField(max_length=100, blank=False, null=False)
    product_id_1 = models.TextField(max_length=100, blank=True, null=True)
    product_id_2 = models.TextField(max_length=100, blank=True, null=True)
    product_id_3 = models.TextField(blank=True, null=True)
    product_id_4 = models.TextField(max_length=1000, blank=True, null=True)
    product_id_5 = models.TextField(max_length=100, blank=True, null=True)
    class Meta:
        """
        表名
        """
        db_table = "users_recommendations"

class Users_AllRecommendations(models.Model):
    """
    与User_Recommendations表中的字段相对应，
    """
    user_id = models.CharField(max_length=100, blank=False, null=False)
    products_id = models.TextField(blank = False, null = False)
    class Meta:
        """
        表名
        """
        db_table = "users_allrecommendations"

apps/recommendations/views.py
# @Time    : 2019/3/10 20:12
# @Author  : Virus
# @Remark  :

import json
import re
from django.shortcuts import render
from django.views.generic.base import View
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from utils.mixin_utils import LoginRequiredMixin
#from .forms import LoginForm, UserCreateForm
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.hashers import make_password
from recommendations.models import Users_Recommendations
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend
from commodity.models import Commodity
from order.models import Transaction
import pandas as pd
class RecommendationsView(LoginRequiredMixin, View):

    """
    推荐页面列表
    """
    def get(self, request):
        # ret = SystemSetup.getSystemSetupLastData()
        return render(request, 'recommendations/recommendations_list.html')

class RecommendationsDetailView(LoginRequiredMixin, View):
    """
    推荐页面详情
    """


    def get(self, request):
        """
        基本思路是，先获取到在URL中携带的User_ID变量
        然后在User_Recommendations表中获取到五个推荐商品
        接着去Commodity表中获取到五个商品详情，然后通过ret传递给Html页面.

        关键是要理解Django架构中的QuerySet类,只能通过迭代器进行访问。
        该方法尚待优化。
        :param request: 网页请求，不赘述
        :return: 返回html页面
        """
        ret = dict()
        print(request.GET)
        if 'user_id' in request.GET and request.GET['user_id']:
            print(request.GET['user_id'])
            recommendations = Users_Recommendations.objects.filter(user_id=request.GET['user_id'])
            commodityidlist = []
            for i in recommendations:
                commodityidlist.append([i.product_id_1, i.product_id_2, i.product_id_3,i.product_id_4,i.product_id_5])
            commoditylist = []
            for item_id in commodityidlist[0]:
                commodity = Commodity.objects.filter(id=item_id)
                commoditylist.append(commodity[0])

            ret['commodity_1'] = commoditylist[0]
            ret['commodity_2'] = commoditylist[1]
            ret['commodity_3'] = commoditylist[2]
            ret['commodity_4'] = commoditylist[3]
            ret['commodity_5'] = commoditylist[4]

        return render(request, 'recommendations/recommendations_details.html', ret)










class RecommendationsListView(LoginRequiredMixin, View):
    """
    推荐列表
    """

    def get(self, request):
        """

        :param request: 网页请求，不赘述

        理解Objet.Filter方法，将列名合并成列表，去数据库中找值。
        :return: html网页
        """
        fields = ['user_id', 'product_id_1', 'product_id_2', 'product_id_3', 'product_id_4', 'product_id_5']
        filters = dict()
        print(request.GET.get('user_id'))
        if 'user_id' in request.GET and request.GET['user_id']:
            filters['user_id__icontains'] = request.GET['user_id']
        if 'product_id_1' in request.GET and request.GET['product_id_1']:
            filters['product_id_1__icontains'] = request.GET['product_id_1']
        if 'product_id_2' in request.GET and request.GET['product_id_2']:
            filters['product_id_2__icontains'] = request.GET['product_id_2']
        if 'product_id_3' in request.GET and request.GET['product_id_3']:
            filters['product_id_3__icontains'] = request.GET['product_id_3']
        if 'product_id_4' in request.GET and request.GET['product_id_4']:
            filters['product_id_4__icontains'] = request.GET['product_id_4']
        if 'product_id_5' in request.GET and request.GET['product_id_5']:
            filters['product_id_5__icontains'] = request.GET['product_id_5']
        ret = dict(data=list(Users_Recommendations.objects.filter(**filters).values(*fields)))

        return HttpResponse(json.dumps(ret, cls=DjangoJSONEncoder), content_type='application/json')

templates/recommendations/recommendations_detail.html
<!--
# @Time    : 2019/3/6 20:00
# @Author  : Virus
# @Remark  :

-->
{% extends "base-left.html" %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
{% endblock %}

{% block content %}


    <!-- Main content -->

  <section class="content">
      <div class="row">
       <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">商品详情</h3>

              <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="box-body no-padding">
                <div class="btn-group pull-right margin-b-10 margin-r-5">

                  <button type="button" class="btn btn-primary btn-sm" title="返回" id="btnReturn">
                      <i class="fa fa-undo"> 返回</i>
                  </button>
                  <button type="button" class="btn btn-info btn-sm" title="编辑" id="doUpdate"
                          onclick="doUpdate({{ commodity.id }})">
                      <i class="fa fa-pencil"> 编辑</i>
                  </button>
                </div>
           </div>


               <div class="table-responsive mailbox-messages">
                  <table class="table" id="tbWorkList"  style="white-space: nowrap;">
                    <tbody>
                        <tr class="info">
                            <td width="10%"><strong>商品编号</strong></td>
                            <td class="text-left" width="50%">{{ commodity.assin }}</td>
                            <td width="10%"><strong>商品类型</strong></td>
                            <td class="text-left">{{ commodity.categories.type_name }}</td>
                        </tr>
                        <tr>
                            <td><strong>名称</strong></td>
                            <td>{{ commodity.title }}</td>
                            <td><strong>品牌</strong></td>
                            <td>{{ commodity.brand }}</td>
                        </tr>
                        <tr class="info">
                            <td><strong>购买日期</strong></td>
                            <td>{{ commodity.buyDate }}</td>
                            <td><strong>质保日期</strong></td>
                            <td>{{ commodity.warrantyDate }}</td>
                        </tr>
                        <tr>
                            <td><strong>价格/元</strong></td>
                            <td>{{ commodity.present_price | default_if_none:"" }}</td>
                            <td><strong>状态</strong></td>
                            <td>{{ commodity.get_status_display }}</td>
                        </tr>


                        <tr class="info">

                            <td><strong>描述</strong></td>
                            <td > <textarea class="form-control" name="description" rows="3">{{ commodity.description }}</textarea></td>
                        </tr>

                    </tbody>
                  </table>

                </div>
               <br>
               <div class="box-footer">
                  <ul class="mailbox-attachments clearfix">

                    <li >
                      <a href="{{ commodity.imUrl }}" target="_blank">
                        <span class="mailbox-attachment-icon has-img" width="70px" height="1000px"><img src="{{ commodity.imUrl }}" alt=""></span>
                      </a>
                    </li>

                  </ul>
                </div>

            <!-- /.box-footer -->
            </div>
            <!-- /.box-body -->
          </div>
      </div>
        <!-- /.col -->
     <!-- TO DO List -->

          <!-- /.box -->

    </section>

    <!-- /.content -->

{% endblock %}

{% block javascripts %}
  <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
  <script type="text/javascript">
  	$(function() {
	    $('#ADM-ASSET').addClass('active');

	});
  	//返回
    $("#btnReturn").click(function(){
		history.back();
	});

    function doUpdate(id){
	var div=layer.open({
		type : 2,
		title : '修改商品信息',
		shadeClose : false,
    	maxmin : true,
		area : [ '800px', '580px' ],
		content : "{% url 'commodity:update' %}"+'?id='+id,
		end : function() {
			//oDataTable.ajax.reload();
            window.location.reload();

		}
	});
	layer.full(div)
}

</script>

{% endblock %}

templates/recommendations/recommendations_details.html
<!--
# @Time    : 2019/3/6 20:00
# @Author  : Virus
# @Remark  :

-->

{% extends "base-left.html" %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
{% endblock %}

{% block content %}


    <!-- Main content -->

  <section class="content">

      <div class="row">
       <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">

              <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="box-body no-padding">
                <div class="btn-group pull-right margin-b-10 margin-r-5">

                  <button type="button" class="btn btn-primary btn-sm" title="返回" id="btnReturn">
                      <i class="fa fa-undo"> 返回</i>
                  </button>

                </div>
           </div>
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title">商品推荐详情</h3>
              </div>
              <div class="panel-body">
                <div class="row">
                    <div class="col-lg-2">
                      <img class="img-circle" src="/media/{{ commodity_1.imUrl }}" alt="Generic placeholder image" width="140" height="140">
                      <h2>{{ commodity_1.short_title }}</h2>
                      <p>{{ commodity_1.short_description }}</p>
                      <p><a class="btn btn-default" href="#" role="button" id = "btn1" onclick = 'doDetail({{ commodity_1.id }})'>查看详情 »</a></p>
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-2">
                      <img class="img-circle" src="/media/{{ commodity_2.imUrl }}" alt="Generic placeholder image" width="140" height="140">
                      <h2>{{ commodity_2.short_title }}</h2>
                      <p>{{ commodity_2.short_description }}</p>
                      <p><a class="btn btn-default" href="#" role="button" id="btn2" onclick = 'doDetail({{ commodity_2.id }})'>查看详情 »</a></p>
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-2">
                      <img class="img-circle" src="/media/{{ commodity_3.imUrl }}" alt="Generic placeholder image" width="140" height="140">
                      <h2>{{ commodity_3.short_title }}</h2>
                      <p>{{ commodity_3.short_description }}</p>
                      <p><a class="btn btn-default" href="#" role="button" id = "btn3" onclick = 'doDetail({{ commodity_3.id }})'>查看详情 »</a></p>
                    </div><!-- /.col-lg-4 -->

                    <div class="col-lg-2">
                      <img class="img-circle" src="/media/{{ commodity_4.imUrl }}" alt="Generic placeholder image" width="140" height="140">
                      <h2>{{ commodity_4.short_title }}</h2>
                      <p>{{ commodity_4.short_description }}</p>
                      <p><a class="btn btn-default" href="#" role="button" id = "btn4" onclick = 'doDetail({{ commodity_4.id }})'>查看详情 »</a></p>
                    </div><!-- /.col-lg-4 -->

                    <div class="col-lg-2">
                      <img class="img-circle" src="/media/{{ commodity_5.imUrl }}" alt="Generic placeholder image" width="140" height="140">
                      <h2>{{ commodity_5.short_title }}</h2>
                      <p>{{ commodity_5.short_description }}</p>
                      <p><a class="btn btn-default" href="#" role="button" id = "btn5" onclick = 'doDetail({{ commodity_5.id }})'>查看详情 »</a></p>
                    </div><!-- /.col-lg-4 -->
                  </div>
              </div>
            </div>




               <br>


            <!-- /.box-footer -->
            </div>
            <!-- /.box-body -->
          </div>
      </div>
        <!-- /.col -->
     <!-- TO DO List -->

          <!-- /.box -->

    </section>

    <!-- /.content -->

{% endblock %}

{% block javascripts %}
  <script src="{% static 'js/plugins/layer/layer.js' %}"></script>

  <script type="text/javascript">
  	$(function() {
	    $('#ADM-ASSET').addClass('active');

	});
  	//返回
    $("#btnReturn").click(function(){
		history.back();
	});

    function doDetail(id) {
            window.location.href = "{% url 'commodity:detail' %}?id=" + id;
    }

    function doUpdate(id){
	var div=layer.open({
		type : 2,
		title : '修改商品信息',
		shadeClose : false,
    	maxmin : true,
		area : [ '800px', '580px' ],
		content : "{% url 'commodity:update' %}"+'?id='+id,
		end : function() {
			//oDataTable.ajax.reload();
            window.location.reload();

		}
	});
	layer.full(div)
}

</script>

{% endblock %}

templates/recommendations/recommendations_list.html
<!--
# @Time    : 2019/3/6 20:00
# @Author  : Virus
# @Remark  :

-->
{% extends "base-left.html" %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.min.css' %}">
<link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
<link rel="stylesheet" href="{%static 'plugins/select2/select2.min.css' %}">
<!-- iCheck for checkboxes and radio inputs -->
{% endblock %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header margin-bottom">
  <ol class="breadcrumb">
    <li><a href=""><i class="fa fa-dashboard"></i>办公平台</a></li>
    <li class="active"><a href="#">资产管理</a></li>
    <li class="active"><a href="#">资产详情</a></li>
  </ol>
</section>

    <!-- Main content -->
  <section class="content">
     <div id="devlist">
        <div class="box box-primary" id="liebiao">
            <div class="box-header">
              <form class="form-inline" id="queryForm">
                <div class="form-group searchArea margin-r-5 margin-top-5">
                    <label>商品编号：</label>
                    <input type="text" name="assin" class="form-control inputText" id="assin">
                </div>
              <div class="form-group searchArea margin-r-5 margin-top-5">
                    <label>商品名称：</label>
                    <input type="text" name="title" class="form-control inputText" id="title">
                </div>

               <div class="form-group searchArea margin-r-5 margin-top-5">
                <label>商品类型：</label>
                <select class="form-control inputText select2" name="categories", id="categories">
                    <option></option>
                    {% for type in commodity_types %}
                    <option value={{ type.id }}>{{ type.type_name }}</option>
                    {% endfor %}
                </select>
              </div>
                <div class="form-group searchArea margin-r-5 margin-top-5">
                    <label>商品品牌：</label>
                    <input type="text" name="brand" class="form-control inputText" id="brand">
                </div>
                 <div class="form-group searchArea margin-r-5 margin-top-5">
                    <label>商品状态：</label>
                     <select class="form-control inputText select2" name="status" id="status">
                        <option></option>
                        {% for status in status_list %}
                        <option value={{ status.item }}>{{ status.value }}</option>
                        {% endfor %}
                    </select>
               </div>
                <button type="button" id="btnCommoditySearch" class="btn btn-default">
                    <i class="glyphicon glyphicon-search"></i>查询
                </button>
            </form>
            </div>
             <div class="box-body">
                <table id="dtbList" class="display" cellspacing="0" width="100%">
                    <thead>
                    <tr valign="middle">
                        <th><input type="checkbox" id="checkAll"></th>
                        <th>用户ID</th>
                        <th>推荐商品1</th>
                        <th>推荐商品2</th>
                        <th>推荐商品3</th>
                        <th>推荐商品4</th>
                        <th>推荐商品5</th>
                        <th>更新时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <br> <br>
            </div>
        </div>
     </div>
  </section>

    <!-- /.content -->

{% endblock %}

{% block javascripts %}
  <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'plugins/datatables/dataTables.const.js' %}"></script>
  <script src="{% static 'plugins/datatables/moment.min.js' %}"></script>
  <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
  <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
  <!-- iCheck 1.0.1 -->
  <script type="text/javascript">
	$(function() {
	    $('#RECOMMENDATIONS-LIST').addClass('active');

	});
  </script>

    <script type="text/javascript">
var oDataTable=null;
$(function() {
	oDataTable = initTable();
	function initTable() {
		var oTable=$('#dtbList').DataTable($.extend(true,{},
						DATATABLES_CONSTANT.DATA_TABLES.DEFAULT_OPTION,
						{
							ajax : {
								"url":"{% url 'recommendations:recommendations-list' %}",
								"data":function ( e ) {
									e.select=$("#select").val();
								}
						},

						columns : [
								DATATABLES_CONSTANT.DATA_TABLES.COLUMN.CHECKBOX,

								{
									data : "user_id",

								},

                                {
									data : "product_id_1",
                                    render : function(data, type, row, meta) {
                                        return data ;
                                        }

								},
                                {
                                    data:"product_id_2",
                                    render : function(data, type, row, meta) {
                                        return data ;
                                        }
                                },
                                {
									data : "product_id_3",
                                    render : function(data, type, row, meta) {
                                        return data ;
                                        }

								},
                                {
									data : "product_id_4",
                                    render : function(data, type, row, meta) {
                                        return data ;
                                        }
								},

                                {   data : "product_id_5",
                                    render : function(data, type, row, meta) {
                                        return data ;
                                        }

								},

                                {
									data : "buyDate",
                                     render : function(data, type, full, meta) {
                                         return  moment(data).format("YYYY-MM-DD HH:mm");}
								},
                                {

                                    data : "user_id",

                                    render: function (data, type, full, meta) {
                                        var ret="<button title='详情' onclick='doDetail(\""+data + "\")'><i class='glyphicon glyphicon-list-alt'></i></button>";

                                        return ret;}
                                }



								 ],
						}));
		return oTable;
	}

   //刷新页面GET查询请求
    $("#btnCommoditySearch").click(function(){
            alert(oDataTable.ajax.all())
            oDataTable.ajax.reload();
        });


	//select选择后刷新页面GET请求
    $("#select").change(function(){
		alert($("#select").val())
		oDataTable.ajax.reload();
	});
	//checkbox全选
    $("#checkAll").on("click", function () {
        if ($(this).prop("checked") === true) {
            $("input[name='checkList']").prop("checked", $(this).prop("checked"));
            $('#example tbody tr').addClass('selected');
        } else {
            $("input[name='checkList']").prop("checked", false);
            $('#example tbody tr').removeClass('selected');
        }
    });


	$("#btnCreate").click(function() {
		var div=layer.open({
			type : 2,
			title : '商品入库',
			shadeClose : false,
			maxmin : true,
			area : [ '800px', '580px' ],
			content : "{% url 'commodity:create' %}",
			end : function() {
				//关闭时做的事情
				window.location.reload();
			}
		});
           layer.full(div)
	});


	//批量删除
	$("#btnDelete").click(function() {
		if ($("input[name='checkList']:checked").length == 0){
			layer.msg("请选择要删除的记录");
			return ;
		}

		var arrId= new Array();
		$("input[name='checkList']:checked").each(function(){
			//alert($(this).val());
			arrId.push($(this).val());
		});

		sId=arrId.join(',');

		layer.alert('确定删除吗？', {
			title:'提示'
			,icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
			,time: 0 //不自动关闭
			,btn: ['YES', 'NO']
			,yes: function(index){
			 	layer.close(index);
			 	$.ajax({
					type: "POST",
					url : "{% url 'commodity:delete' %}",
					data : {"id":sId, csrfmiddlewaretoken: '{{ csrf_token }}'},
					cache: false,
					success : function(msg) {
						if (msg.result){
							layer.alert("操作成功",{icon:1});
							oDataTable.ajax.reload();
						}else{
							//alert(msg.message);
							layer.alert("操作失败",{icon:2});
						}
						return ;
					}
				});
			}
		});
	});


});

function doDetail(id){
    console.log(id);
    window.location.href="{% url 'recommendations:detail' %}?user_id="+id;
}


function doUpdate(id){
	var div=layer.open({
		type : 2,
		title : '修改商品信息',
		shadeClose : false,
    	maxmin : true,
		area : [ '800px', '580px' ],
		content : "{% url 'commodity:update' %}"+'?id='+id,
		end : function() {
			//oDataTable.ajax.reload();
            window.location.reload();

		}
	});
	layer.full(div)
}

//删除单个数据
function doDelete(id){
    layer.alert('确定删除吗？', {
        title:'提示'
        ,icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
        ,time: 0 //不自动关闭
        ,btn: ['YES', 'NO']
        ,yes: function(index){
            layer.close(index);
            $.ajax({
                type: "POST",
                url : "{% url 'commodity:delete' %}",
                data : {"id":id, csrfmiddlewaretoken: '{{ csrf_token }}'},  //防止post数据时报 csrf_token 403
                cache: false,
                success : function(msg) {
                    if (msg.result){
                        layer.alert('删除成功',{icon: 1});
                        oDataTable.ajax.reload();
                    }else{
                        //alert(msg.message);
                        layer.alert('删除失败', {icon: 2});
                    }
                    return ;
                }
            });
        }
    });

}
</script>
<script>
  $(function () {
    //Initialize Select2 Elements
    $(".select2").select2();
  });
</script>
{% endblock %}