apps/commodity/urls.py
from django.conf.urls import url

from commodity import views

urlpatterns = [

    url(r'commodity/$', views.CommodityView.as_view(), name='commodity'),
    url(r'^commodity/list$', views.CommodityListView.as_view(), name="commodity-list"),
    url(r'^commodity/create$', views.CommodityCreateView.as_view(), name="create"),
    url(r'^commodity/update$', views.CommodityUpdateView.as_view(), name="update"),
    url(r'^commodity/delete$', views.CommodityDeleteView.as_view(), name='delete'),
    url(r'^commodity/enable$', views.CommodityEnableView.as_view(), name='enable'),
    url(r'^commodity/disable$', views.CommodityDisableView.as_view(), name='disable'),
    url(r'^commodity/detail$', views.CommodityDetailView.as_view(), name="detail"),
    url(r'^commodity/uploadimage$', views.UploadImageView.as_view(), name="commodity-uploadimage"),
]

reporjectred/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from reporjectred.settings import MEDIA_ROOT
from users.views import IndexView, LoginView, LogoutView
from personal.views import PersonalView, UserInfoView, UploadImageView, \
    PasswdChangeView
from api.views_member import FaceView


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^$', IndexView.as_view(), name='index'),
    # 用户登录
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),

    url(r'^personal/$', PersonalView.as_view(), name="personal"),
    url(r'^personal/userinfo', UserInfoView.as_view(), name="personal-user_info"),
    url(r'^personal/uploadimage', UploadImageView.as_view(), name="personal-uploadimage"),
    url(r'^personal/passwordchange', PasswdChangeView.as_view(), name="personal-passwordchange"),

    url(r'^users/', include('users.urls', namespace='users')),

    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^commodity/', include('commodity.urls', namespace='commodity')),

    url(r'^recommendations/', include('recommendations.urls', namespace='recommendations')),
    url(r'^comment/', include('apps.comment.urls', namespace='comment')),

    url(r'^hotcommend/', include('hotcommend.urls', namespace='hotcommend')),

    url(r'^api/face/$', FaceView.as_view(), name="face"),

    url(r'^api/', include('api.urls', namespace='api')),
]

apps/commodity/models.py
# @Time    : 2019年3月5日19:54:50
# @Author  : xie Liangcai
# @Remark  : 商品种类，信息，价格model


from django.db import models
import django.utils.timezone as timezone


# 商品类别表
class CommodityType(models.Model):
    '''
    商品类型model
    '''
    type_name = models.CharField(max_length=1000)
    description = models.CharField(max_length=1000, blank=True, null=True)

    class Meta:
        db_table = "commodity_type"


# 商品列表
class Commodity(models.Model):
    '''
       商品信息model
    '''
    commodity_status = (
        ("0", "下架"),
        ("1", "在售"),
    )
    assin = models.CharField(max_length=100, blank=False, null=False)
    categories = models.ForeignKey(CommodityType, on_delete=models.SET_NULL, blank=True, null=True)
    present_price = models.FloatField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    title = models.CharField(max_length=1000, blank=True, null=True)
    # imUrl = models.ImageField(upload_to="commImage",default="commImage/default.jpg")
    imUrl = models.CharField(max_length=1000, blank=True, null=True)
    brand = models.CharField(max_length=1000, blank=True, null=True)
    buyDate = models.DateTimeField('商品购买日期', blank=True, null=True, default=timezone.now)
    warrantyDate = models.DateTimeField('商品保质日期', blank=True, null=True, default=timezone.now)
    status = models.CharField(choices=commodity_status, max_length=20, default="1", verbose_name="商品的状态")

    def short_description(self):
        if len(str(self.description)) > 400:
            return '{}...'.format(str(self.description)[0:400])
        else:
            return str(self.description)

    def short_title(self):

        if len(str(self.title)) > 50:
            return '{}...'.format(str(self.title)[0:50])
        else:
            return str(self.title)

    class Meta:
        db_table = "commodity"


# 商品价格表
class Commodity_price(models.Model):
    '''
       商品价格model
    '''
    asin = models.ForeignKey(Commodity)
    price = models.FloatField(default=0, blank=True)
    updataTime = models.DateTimeField('价格更新日期', auto_now_add=True)
    description = models.CharField(max_length=1000, blank=True, null=True)

    class Meta:
        db_table = "commodity_price"

apps/commodity/forms.py
from django import forms
from commodity.models import Commodity, CommodityType, Commodity_price


class CommodityCreateForm(forms.ModelForm):

    class Meta:
        model = Commodity
        fields = ['assin','status']

        error_messages = {
            "assin": {"required": "商品编号不能为空"},
            "status": {"required": "请选择商品状态"},
        }

    def clean(self):
        cleaned_data = super(CommodityCreateForm, self).clean()
        assin = cleaned_data.get("assin")

        if Commodity.objects.filter(assin=assin).count():
            raise forms.ValidationError('资产编号：{}已存在'.format(assin))



class CommodityUpdateForm(forms.ModelForm):

    class Meta:
        model = Commodity
        fields = '__all__'
        error_messages = {
            "assin": {"required": "商品编号不能为空"},
            "title": {"required": "请输入商品名称"},
            # "present_price": {},
            "buyDate": {"required": "请输入购买日期"},
            "warrantyDate": {"required": "请输入质保日期"},
            "status": {"required": "请选择商品状态"}
        }

apps/commodity/views.py
import json
import re
import os
from django.shortcuts import render
from django.views.generic.base import View
from django.http import HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
from commodity.models import Commodity, CommodityType
from commodity.forms import CommodityCreateForm, CommodityUpdateForm
from utils.mixin_utils import LoginRequiredMixin


class CommodityView(LoginRequiredMixin, View):

    def get(self, request):
        '''
        get方法
        :param request:
        :return:跳转到商品列表页面
        '''
        ret = dict()
        status_list = []
        for status in Commodity.commodity_status:
            status_dict = dict(item=status[0], value=status[1])
            status_list.append(status_dict)
        commodity_types = CommodityType.objects.all()
        ret['status_list'] = status_list
        ret['commodity_types'] = commodity_types
        return render(request, 'commodity/commodity_list.html', ret)


class CommodityListView(LoginRequiredMixin, View):
    """商品显示页面"""

    def get(self, request):
        '''
        get方法
        :param request:
        :return: 返回商品信息列表到前端
        '''
        fields = ['id', 'assin', 'title', 'brand', 'status', 'buyDate', 'present_price', 'categories__type_name']
        filters = dict()
        if 'assin' in request.GET and request.GET['assin']:
            filters['assin__icontains'] = request.GET['assin']
        if 'title' in request.GET and request.GET['title']:
            filters['title__icontains'] = request.GET['title']
        if 'categories' in request.GET and request.GET['categories']:
            filters['categories'] = request.GET['categories']
        if 'status' in request.GET and request.GET['status']:
            filters['status'] = request.GET['status']

        commodity_list = Commodity.objects.filter(**filters).values(*fields)
        for commodity in commodity_list:
            title = commodity['title']
            if len(str(title)) > 50:
                commodity['title'] = '{}...'.format(str(title)[0:50])

        ret = json.dumps(dict(data=list(commodity_list)), cls=DjangoJSONEncoder)

        return HttpResponse(ret, content_type='application/json')


class CommodityCreateView(LoginRequiredMixin, View):
    """添加商品页面"""

    def get(self, request):
        '''

        :param request:
        :return:跳转到添加商品页面
        '''
        ret = dict()
        status_list = []
        for status in Commodity.commodity_status:
            status_dict = dict(item=status[0], value=status[1])
            status_list.append(status_dict)
        commodity_type = CommodityType.objects.all()
        ret['commodity_type'] = commodity_type
        ret['status_list'] = status_list
        return render(request, 'commodity/commodity_create.html', ret)

    def post(self, request):
        res = dict()
        commodity_create_form = CommodityCreateForm(request.POST, request.FILES)
        if commodity_create_form.is_valid():
            commodity_create_form.save()
            res['status'] = 'success'
        else:
            pattern = '<li>.*?<ul class=.*?><li>(.*?)</li>'
            errors = str(commodity_create_form.errors)
            commodity_form_errors = re.findall(pattern, errors)
            res = {
                'status': 'fail',
                'commodity_form_errors': commodity_form_errors[0]
            }
        return HttpResponse(json.dumps(res), content_type='application/json')


class CommodityUpdateView(LoginRequiredMixin, View):
    """商品信息修改页面"""

    def get(self, request):
        '''

        :param request:
        :return: 跳转到修改商品信息页面
        '''
        ret = dict()
        status_list = []
        if 'id' in request.GET and request.GET['id']:
            commodity = Commodity.objects.filter(id=request.GET['id'])
            ret['commodity'] = commodity[0]
        for status in Commodity.commodity_status:
            status_dict = dict(item=status[0], value=status[1])
            status_list.append(status_dict)
        commodity_type = CommodityType.objects.values()
        ret['commodity_type'] = commodity_type
        ret['status_list'] = status_list
        return render(request, 'commodity/commodity_update.html', ret)

    def post(self, request):
        res = dict()
        commodity = Commodity.objects.filter(assin=request.GET['assin'])[0]
        commodity_update_form = CommodityUpdateForm(request.POST, instance=commodity)
        if commodity_update_form.is_valid():
            commodity_update_form.save()
            res['status'] = 'success'
        else:
            pattern = '<li>.*?<ul class=.*?><li>(.*?)</li>'
            errors = str(commodity_update_form.errors)
            commodity_form_errors = re.findall(pattern, errors)
            res = {
                'status': 'fail',
                'commodity_form_errors': commodity_form_errors[0]
            }
        return HttpResponse(json.dumps(res), content_type='application/json')


class CommodityDeleteView(LoginRequiredMixin, View):
    '''

        :param request:
        :return: 返回商品删除成功信息
    '''

    def post(self, request):
        ret = dict(result=False)
        if 'id' in request.POST and request.POST['id']:
            id_list = map(int, request.POST.get('id').split(','))
            Commodity.objects.filter(id__in=id_list).delete()

        ret['result'] = True
        return HttpResponse(json.dumps(ret), content_type='application/json')


class CommodityEnableView(LoginRequiredMixin, View):
    '''
       上架商品视图
    '''

    def post(self, request):
        '''
        post方法
        :param request: 页面的request请求
        :return: 返回商品上架成功的信息
        '''
        if 'id' in request.POST and request.POST['id']:
            id_nums = request.POST.get('id')
            queryset = Commodity.objects.extra(where=["id IN(" + id_nums + ")"])
            queryset.filter(status='0').update(status='1')
            ret = {'result': 'True'}
        return HttpResponse(json.dumps(ret), content_type='application/json')


class CommodityDisableView(LoginRequiredMixin, View):
    '''下架商品视图'''

    def post(self, request):
        '''
        :param request:
        :return: 返回商品下架成功信息
        '''

        if 'id' in request.POST and request.POST['id']:
            id_nums = request.POST.get('id')
            queryset = Commodity.objects.extra(where=["id IN(" + id_nums + ")"])
            queryset.filter(status='1').update(status='0')
            ret = {'result': 'True'}
        return HttpResponse(json.dumps(ret), content_type='application/json')


class CommodityDetailView(LoginRequiredMixin, View):
    """商品详情页面"""

    def get(self, request):
        '''
        :param request:
        :return: 跳转到商品详情页面
        '''
        ret = dict()
        if 'id' in request.GET and request.GET['id']:
            commodity = Commodity.objects.filter(id=request.GET['id'])
            ret['commodity'] = commodity[0]
        return render(request, 'commodity/commodity_detail.html', ret)


class UploadImageView(LoginRequiredMixin, View):
    '''
        上传商品图片
    '''

    def get(self, request):
        ret = dict()
        assin = request.GET['assin']
        categories = request.GET['categories']
        ret['assin'] = assin
        ret['categories'] = categories
        print("Image get()")
        return render(request, 'commodity/commodity_upload.html', ret)

    def post(self, request):
        res = dict(status='fail')
        File = request.FILES.get("file_content")
        print(File.name)
        accessory_dir = "media/commImage/" + request.POST['categories']
        if not os.path.isdir(accessory_dir):  # 判断是否有这个目录，没有就创建
            os.mkdir(accessory_dir)
        filename = accessory_dir + "/" + request.POST['assin'] + ".jpg"
        print(filename)
        with open(filename, 'wb+') as f:
            # 分块写入文件
            for chunk in File.chunks():
                f.write(chunk)
        res['status'] = 'success'
        return HttpResponse(json.dumps(res, cls=DjangoJSONEncoder), content_type='application/json')

templates/commodity/commodity_create.html
<!--
@Time    : 2019年3月5日19:54:50
@Author  : xie Liangcai
@Remark  : 添加商品信息页面

-->


{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/fileinput/fileinput.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/combo-select/combo.select.css' %}">
    <link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block main %}
    <div class="box box-danger">
        <form class="form-horizontal" id="addForm" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="box-body">
                <fieldset>
                    <legend>
                    </legend>
                    <div class="form-group has-feedback">
                        <input class="form-control" name="operator" type="hidden" value="{{ request.user.name }}"/>
                        <label class="col-sm-2 control-label">商品编号</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="assin" type="text" id="assin"/>
                        </div>
                        <label class="col-sm-2 control-label">商品类型</label>
                        <div class="col-sm-3">

                            <input id="imUrl1" type="hidden" name="imUrl" value=""/>

                            <select class="form-control select2" style="width:100%;" id="categories">
                                <option></option>
                                {% for type in commodity_type %}
                                    <option value="{{ type.type_name }}">{{ type.type_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">商品名称</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="title" type="text"/>
                        </div>
                        <label class="col-sm-2 control-label">品牌</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="brand" type="text"/>
                        </div>

                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">购买日期</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control pull-right form_datetime" name="buyDate"/>
                        </div>
                        <label class="col-sm-2 control-label">质保日期</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control pull-right form_datetime" name="warrantyDate"/>
                        </div>

                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">价格</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="present_price" type="text"/>
                        </div>
                        <label class="col-sm-2 control-label">商品状态</label>
                        <div class="col-sm-3">
                            <select class="form-control select2" style="width:100%;" name="status">
                                {% for status in status_list %}
                                    <option value="{{ status.item }}">{{ status.value }}</option>
                                {% endfor %}
                            </select>
                        </div>

                    </div>


                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">备注信息</label>
                        <div class="col-sm-3">
                            <textarea class="form-control" name="description" rows="2"></textarea>
                        </div>
                    </div>

{#                        <div class="col-sm-3">#}
{#                            <textarea class="form-control" name="desc" rows="3"></textarea>#}
{#                        </div>#}
                         <div class="form-group has-feedback">
                             <label class="col-sm-2 control-label"> </label>
{#                                <button type="button" id="btnImport"  class="btn btn-primary" data-toggle="modal"  data-target="#exampleModal">#}
{#						             上传图片#}
{#					             </button>#}
{#                             <input type="file" class="file" name="imUrl"/>#}

                             <button type="button" class="btn btn-default btn-sm" onclick="doAssetUpload()">
                                      <i class="fa fa-cloud-upload">上传图片</i>
                             </button>

                         </div>

                </fieldset>

            </div>
            <div class="box-footer ">
                <div class="row span7 text-center ">
                    <button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
                    <button type="button" id="btnSave" class="btn btn-info margin-right ">保存</button>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'plugins/fileinput/fileinput.js' %}"></script>
    <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
    <script src="{% static 'plugins/ajaxfileupload/ajaxfile-upload.js' %}"></script>
    <script src="{% static 'plugins/fileinput/zh.js' %}"></script>
    <script src="{% static 'plugins/combo-select/jquery.combo.select.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


    <script type="text/javascript">

        $("#btnSave").click(function () {
            var categories = document.getElementById("categories").value;
            var assin=$("#assin").val();
            var imUrl="CommImage/"+categories+"/"+assin+".jpg";
            document.getElementById('imUrl1').value=imUrl;
            var data = $("#addForm").serialize();
            $.ajax({
                {#async : false,#}
                type: $("#addForm").attr('method'),
                url: "{% url 'commodity:create' %}",
                {#url:"/commodity/commodity/create",#}
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.status == 'success') {
                        layer.alert('数据保存成功！', {icon: 1}, function (index) {
                            parent.layer.closeAll(); //关闭所有弹窗
                        });
                    } else if (msg.status == 'fail') {
                        console.log(msg);
                        layer.alert(msg.commodity_form_errors, {icon: 5});
                    }
                    return;
                }
            });
        });

        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();

        });


        /*input 时间输入选择*/
        $(".form_datetime").datetimepicker({
            language: 'zh',
            minView: 'month', //选择范围知道日期，不选择时分
            autoclose: 1,
            todayHighlight: 1,
            forceParse: 0,
            showMeridian: 1,
            format: 'yyyy-mm-dd'
        }).on('changeDate', function (ev) {
            $(this).datetimepicker('hide');
        });

        // select2
        $(function () {
            $(".select2").select2();
        });


         //上传商品图片
        function doAssetUpload(){

            var categories = document.getElementById("categories").value;
            var assin = $("#assin").val();

            if (!assin) {
                var msg = "请先填写商品编号！"
                layer.alert(msg, {icon: 5});
            }
            else if(!categories) {
                var msg = "请先填写商品类别！"
                layer.alert(msg, {icon: 5});
            }
            else{
                var div = layer.open({
                    type: 2,
                    title: '上传图片',
                    shadeClose: false,
                    maxmin: true,
                    area: ['770px', '400px'],
                    content: ["{% url 'commodity:commodity-uploadimage' %}" + '?assin=' + assin + '&categories=' + categories],
                    end: function () {
                        {#window.location.reload();#}

                    }
                });
                layer.full(div)
            }

        }

    </script>

{% endblock %}

templates/commodity/commodity_update.html
<!--
@Time    : 2019年3月5日19:54:50
@Author  : xie Liangcai
@Remark  : 更新商品详细信息页面

-->


{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{%static 'plugins/select2/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block main %}
<div class="box box-danger">
	<form class="form-horizontal" id="addForm" method="post">

		{% csrf_token %}
		<div class="box-body">
          <fieldset>
            <legend>
            </legend>
            <div class="form-group has-feedback">
                <input class="form-control" name="operator" type="hidden" value="{{ commodity.operator }}"/>
                <input class="form-control" name="id" type="hidden" value="{{ commodity.id }}"/>
                <label class="col-sm-2 control-label">商品编号</label>
                <div class="col-sm-3">
                    <input class="form-control" name="assin" type="text" value="{{ commodity.assin }}"/>
                </div>
                <label class="col-sm-2 control-label">类型</label>
                <div class="col-sm-3">
                  <select class="form-control select2" style="width:100%;" name="categories">
                  <option value="{{commodity.categories_id}}">{{ commodity.categories.type_name }}</option>
                  {% for type in commodity_type %}
                  <option value="{{ type.id }}">{{ type.type_name }}</option>
                  {% endfor %}
                 </select>
                </div>
            </div>
            <div class="form-group has-feedback">
                <label class="col-sm-2 control-label">商品名称</label>
                <div class="col-sm-3">
                    <input class="form-control" name="title" type="text" value="{{ commodity.title }}"/>
                </div>
                <label class="col-sm-2 control-label">品牌</label>
                <div class="col-sm-3">
                    <input class="form-control" name="brand" type="text" value="{{ commodity.brand }}"/>
                </div>

            </div>
            <div class="form-group has-feedback">
                <label class="col-sm-2 control-label">购买日期</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control pull-right form_datetime" name="buyDate" value="{{ commodity.buyDate|date:'Y-m-d' }}"/>
                </div>
                <label class="col-sm-2 control-label">质保日期</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control pull-right form_datetime" name="warrantyDate" value="{{ commodity.warrantyDate |date:'Y-m-d' }}"/>
                </div>
            </div>
            <div class="form-group has-feedback">

                 <label class="col-sm-2 control-label">价格</label>
                <div class="col-sm-3">
                    <input class="form-control" name="present_price" type="text" value="{{ commodity.present_price | default_if_none:"" }}"/>
                </div>

                <label class="col-sm-2 control-label">商品状态</label>
                <div class="col-sm-3">
                  <select class="form-control select2" style="width:100%;" name="status">
                  <option value="{{ commodity.status }}">{{ commodity.get_status_display }}</option>
                  {% for status in status_list %}
                  <option value="{{ status.item }}">{{ status.value }}</option>
                  {% endfor %}
                 </select>
                </div>

            </div>



            <div class="form-group has-feedback">
                <label class="col-sm-2 control-label">备注信息</label>
                <div class="col-sm-3">
                    <textarea class="form-control" name="description" rows="5" value="{{ commodity.description }}">{{ commodity.description }}</textarea>
                </div>
                <label class="col-sm-2 control-label">商品图片</label>
                <div class="col-sm-3">
{#                    <a href="/media/{{ commodity.imUrl }}" target="_blank">#}
                        <span class="mailbox-attachment-icon has-img"><img src="/media/{{ commodity.imUrl }}" alt="" width="300px" height="300px "></span>
{#                      </a>#}
{#                    <button type="button" id="btnImport"  class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">#}
{#						修改图片#}
{#					</button>#}
                </div>
            </div>

          </fieldset>
		</div>
		<div class="box-footer ">
			<div class="row span7 text-center ">
              <button type="button" id="btnCancel" class="btn btn-default margin-right " >重置</button>
              <button type="button" id="btnSave" class="btn btn-info margin-right " >保存</button>
			</div>
		</div>

	</form>
</div>


{% endblock %}

{% block javascripts %}
<script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
<script type="text/javascript">

	$("#btnSave").click(function(){
		var data = $("#addForm").serialize();
		$.ajax({
			type: $("#addForm").attr('method'),
			url : "{% url 'commodity:update' %}",
			data : data,
			cache: false,
			success : function(msg) {
				if (msg.status == 'success'){
					layer.alert('数据保存成功！', {icon: 1},function(index){
					    parent.layer.closeAll(); //关闭所有弹窗
                    });
				}else if (msg.status == 'fail'){
					layer.alert(msg.commodity_form_errors, {icon: 5});
				}
				return ;
			}
		});
	});

	/*点取消刷新新页面*/
    $("#btnCancel").click(function () {
	    window.location.reload();

    })

/*通过按钮关闭弹layer弹出的页面窗口*/
{#    $(document).ready(function(){#}
{#        $("#btnCancel").click(function(){#}
{#            var index = parent.layer.getFrameIndex(window.name); //获取窗口索引#}
{#            parent.layer.close(index);//关闭窗口#}
{#        });#}
{#    });#}

/*input 时间输入选择*/
    $(".form_datetime").datetimepicker({
            language:  'zh',
            minView: 'month', //选择范围知道日期，不选择时分
            //weekStart: 1,
            //todayBtn:  1,
            autoclose: 1,
            todayHighlight: 1,
            //startView: 2,
            forceParse: 0,
            showMeridian: 1,
            format: 'yyyy-mm-dd'
        }).on('changeDate', function (ev) {
            $(this).datetimepicker('hide');
    });

// select2
  $(function () {
    //Initialize Select2 Elements
    $(".select2").select2();
  });

  //上传头像图片
$(document).on('ready', function() {
    $("#input-b9").fileinput({
        showPreview: true,
        showUpload: true,
        uploadExtraData: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
        language: "zh",
        elErrorContainer: '#kartik-file-errors',
        allowedFileExtensions: ["jpg", "png", "gif"],
        uploadUrl: '{% url "commodity:commodity-uploadimage" %}',
        maxImageWidth: 500,
        maxImageHeight: 500,

    });
});

</script>

{% endblock %}