apps/users/urls.py
from django.conf.urls import url

from users import views

urlpatterns = [
    # 用户增改删查操作
    url(r'^user/$', views.UserView.as_view(), name="user"),
    url(r'^user/list$', views.UserListView.as_view(), name="user-list"),
    url(r'^user/create$', views.UserCreateView.as_view(), name="user-create"),
    url(r'^user/enable$', views.UserEnableView.as_view(), name="user-enable"),
    url(r'^user/disable$', views.UserDisableView.as_view(), name="user-disable"),
    url(r'^user/delete$', views.UserDeleteView.as_view(), name="user-delete"),
    # url(r'^user/detail$', views_user.UserDetailView.as_view(), name="user-detail"),
    # url(r'^user/update$', views_user.UserUpdataView.as_view(), name="user-update"),
    # url(r'^user/create$', views_user.UserCreateView.as_view(), name="user-create"),
    # url(r'^user/delete$', views_user.UserDeleteView.as_view(), name="user-delete"),
    # url(r'^user/enable$', views_user.UserEnableView.as_view(), name="user-enable"),
    # url(r'^user/disable$', views_user.UserDisableView.as_view(), name="user-disable"),
    # url(r'^user/adminpasswdchange$', views_user.AdminPasswdChangeView.as_view(), name="user-adminpasswdchange"),

]

reporjectred/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from reporjectred.settings import MEDIA_ROOT
from users.views import IndexView, LoginView, LogoutView
from personal.views import PersonalView, UserInfoView, UploadImageView, \
    PasswdChangeView
from api.views_member import FaceView


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^$', IndexView.as_view(), name='index'),
    # 用户登录
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),

    url(r'^personal/$', PersonalView.as_view(), name="personal"),
    url(r'^personal/userinfo', UserInfoView.as_view(), name="personal-user_info"),
    url(r'^personal/uploadimage', UploadImageView.as_view(), name="personal-uploadimage"),
    url(r'^personal/passwordchange', PasswdChangeView.as_view(), name="personal-passwordchange"),

    url(r'^users/', include('users.urls', namespace='users')),

    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^commodity/', include('commodity.urls', namespace='commodity')),

    url(r'^recommendations/', include('recommendations.urls', namespace='recommendations')),
    url(r'^comment/', include('apps.comment.urls', namespace='comment')),

    url(r'^hotcommend/', include('hotcommend.urls', namespace='hotcommend')),

    url(r'^api/face/$', FaceView.as_view(), name="face"),

    url(r'^api/', include('api.urls', namespace='api')),
]

apps/api/models.py
from django.db import models

from commodity.models import Commodity


class Member(models.Model):
    gender_choices = (('1', '男'), ('2', '女'))
    state_choices = (('0', '正常'), ('1', '锁定'))
    type_choices = (('0', '普通用户'), ('1', '高级用户'))

    openid = models.CharField(max_length=100, null=True, blank=True, verbose_name="openid", default=0)
    faceid = models.CharField(max_length=128, null=True, blank=True, verbose_name="faceid")
    face_json = models.TextField(null=True, blank=True, verbose_name="人脸信息")
    pic_name = models.CharField(max_length=100, null=True, blank=True, verbose_name="人脸图片位置")
    joined_date1 = models.DateField(null=True, blank=True, verbose_name="人脸录入时间")
    joined_date2 = models.DateField(null=True, blank=True, verbose_name="用户注册时间", default='2019-01-01')

    nickname = models.CharField(null=True, blank=True, max_length=20, verbose_name="昵称", default='暂无')
    gender = models.CharField(null=True, blank=True, max_length=4, choices=gender_choices, verbose_name="性别",
                              default='暂无')
    avatarUrl = models.CharField(max_length=200, verbose_name="头像链接", null=True, blank=True, default='暂无')
    city = models.CharField(null=True, blank=True, max_length=20, verbose_name="城市", default='暂无')
    province = models.CharField(null=True, blank=True, max_length=20, verbose_name="省份", default='暂无')
    state = models.CharField(null=True, blank=True, max_length=4, choices=state_choices, default='0',
                             verbose_name="会员状态")
    codeVerify = models.CharField(null=True, blank=True, max_length=6, verbose_name="验证码", default='-1')
    type = models.CharField(null=True, blank=True, max_length=4, choices=type_choices, default='0', verbose_name="会员级别")
    last_login_date = models.DateTimeField(null=True, blank=True, verbose_name="上次登录时间", default='2019-01-01')

    class Meta:
        verbose_name = "会员基本信息"
        verbose_name_plural = verbose_name
        ordering = ["id"]

    # def __str__(self):
    #     return self.nickname


class Remark(models.Model):
    """
    评论表的相对信息
    """
    pass


class Credit(models.Model):
    '''
    √0：每日首次登陆获得积分：+2分/次
    √1：消费送积分：+1分/元
    √2：每日首次转发送积分：+3分/次
    ×3：发表评论送积分：+2分/条
    ×4：消费抵扣积分：-1元/100分
    '''
    type_choices = (('0', '收入'), ('1', '支出'))
    bahave_choices = (('0', '每日首次登陆加积分'), ('1', '消费送积分'), ('2', '转发送积分'), ('3', '发表评论送积分'), ('4', '消费抵扣积分'))

    behave = models.CharField(null=True, blank=True, max_length=50, choices=bahave_choices, verbose_name='产生积分变动的行为')
    creditpoints = models.IntegerField(null=True, blank=True, verbose_name='每条行为对应的积分')
    credittype = models.CharField(null=True, blank=True, max_length=4, choices=type_choices, verbose_name='积分变动类型')
    createtime = models.DateTimeField(null=True, blank=True, verbose_name='积分变动时间')
    userid = models.ForeignKey(Member, on_delete=models.CASCADE, null=True, blank=True, verbose_name='产生积分变动的用户id')

    class Meta:
        verbose_name = "会员积分变动信息表"
        verbose_name_plural = verbose_name
        ordering = ["createtime"]


class Cart(models.Model):
    commodity = models.ForeignKey(Commodity, on_delete=models.CASCADE, null=True, blank=True, verbose_name='收藏商品id')
    member = models.ForeignKey(Member, on_delete=models.CASCADE, null=True, blank=True, verbose_name='用户id')

    class Meta:
        verbose_name = "商品收藏表"

apps/users/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser


class UserProfile(AbstractUser):
    """
    用户: makemigration提示错误：sers.UserProfile.user_permissions: (fields.E304)，
    需要在settings中指定自定义认证模型：AUTH_USER_MODEL = 'users.UserProfile'
    """

    type_choices = (("0", "超级管理员"), ("1", "分配部门"), ("2", "商家"))

    name = models.CharField(max_length=20, default="", verbose_name="姓名")
    # birthday = models.DateField(null=True, blank=True, verbose_name="出生日期")
    # gender = models.CharField(max_length=10, choices=(("male", "男"), ("famale", "女")), default="male",
    #                           verbose_name="性别")
    mobile = models.CharField(max_length=11, default="", verbose_name="电话")
    email = models.EmailField(max_length=100, verbose_name="邮箱")
    image = models.ImageField(upload_to="image/%Y/%m", default="image/default.jpg", max_length=100, null=True,
                              blank=True)
    type = models.CharField(max_length=20, choices=type_choices, default="2", verbose_name="类型")
    # department = models.ForeignKey("Structure", null=True, blank=True, verbose_name="部门")
    # post = models.CharField(max_length=50, null=True, blank=True, verbose_name="职位")
    # superior = models.ForeignKey("self", null=True, blank=True, verbose_name="上级主管")
    # roles = models.ManyToManyField("rbac.Role", verbose_name="角色", blank=True)
    url = models.CharField(max_length=100, default="", verbose_name="摄像头路径")
    joined_date = models.DateField(null=True, blank=True, verbose_name="入职日期")

    class Meta:
        verbose_name = "商家信息"
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

apps/users/forms.py
import re

from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(required=True, error_messages={"required": "请填写用户名"})
    password = forms.CharField(required=True, error_messages={"required": u"请填写密码"})


class AdminPasswdChangeForm(forms.Form):
    """
    管理员用户修改用户列表中的用户密码
    """
    # def __init__(self, *args, **kwargs):
    #     super(AdminPasswdChangeForm, self).__init__(*args, **kwargs)
    password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"密码不能为空"
        })

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"确认密码不能为空"
        })

    def clean(self):
        cleaned_data = super(AdminPasswdChangeForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")


class UserCreateForm(forms.ModelForm):
    """
    创建用户表单，进行字段验证
    """

    password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"密码不能为空",
            "min_length": "密码长度最少6位数",
        })

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"确认密码不能为空",
            "min_length": "密码长度最少6位数",
        })

    class Meta:
        model = User
        fields = ['name', 'username', 'mobile',
                  'email', 'joined_date', 'url',
                  'is_active', 'password']

        error_messages = {
            "name": {"required": "姓名不能为空"},
            "username": {"required": "用户名不能为空"},
            "email": {"required": "邮箱不能为空"},
            "mobile": {
                    "required": "手机号码不能为空",
                    "max_length": "输入有效的手机号码",
                    "min_length": "输入有效的手机号码"
            }
        }

apps/users/views.py
# @Author  : cheertt
# @Time    : 2019/3/3 9:44
# @Remark  : 超级管理员以及商家管理模块
import json
import re
from django.shortcuts import render
from django.views.generic.base import View
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from utils.mixin_utils import LoginRequiredMixin
from .forms import LoginForm, UserCreateForm
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.hashers import make_password
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend
User = get_user_model()


class UserBackend(ModelBackend):
    """
    自定义用户验证: setting中对应配置
    AUTHENTICATION_BACKENDS = (
        'users.views.UserBackend',
        )
    """
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            user = User.objects.get(Q(username=username) | Q(mobile=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


class IndexView(LoginRequiredMixin, View):
    """
    跳转首页视图，其中LoginRequiredMixin用于判断当前用户是否处于登陆状态
    """
    def get(self, request):
        return HttpResponseRedirect('/personal/')


class LoginView(View):
    """
    用户登录认证，通过form表单进行输入合规验证
    django使用会话和中间件来拦截认证系统中的请求对象。他们在每一个请求上都提供一个request.user属性，
    表示当前用户。如果当前用户没有接入，该属性将设置成AnonymousUser的一个实例，否则将会是User实例；
    """
    def get(self, request):
        """
        若用户没有被授权，则跳转到登陆页面，否则显示登陆成功主界面
        :param request:
        :return:
        """
        if not request.user.is_authenticated():
            return render(request, 'users/login.html')
        else:
            return HttpResponseRedirect('/personal/')

    def post(self, request):
        """
        若用户状态为0，在登陆页面显示为未激活；
        若输入用户名与密码与数据库不一致，在登陆界面显示用户名或密码错误；
        若用户没有输入用户名或者密码，在登陆页面显示用户名或密码错误；
        否则，用户登陆成功，保存用户信息至session，并显示跳转之后的主界面；
        :param request:
        :return:
        """
        redirect_to = request.GET.get('next', '/personal/')
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_name = request.POST.get("username", "")
            pass_word = request.POST.get("password", "")
            # 认证用户，如果通过认证后端检查，则返回一个user对象
            user = authenticate(username=user_name, password=pass_word)
            if user is not None:
                if user.is_active:
                    # 用来从视图中登陆一个用户，同时将用户id保存在session中
                    # 使用前必须使用authenticate成功认证这个用户
                    login(request, user)
                    return HttpResponseRedirect(redirect_to)
                else:
                    msg = "用户未激活！"
                    ret = {"msg": msg, "login_form": login_form}
                    return render(request, "users/login.html", ret)
            else:
                msg = "用户名或密码错误！"
                ret = {"msg": msg, "login_form": login_form}
                return render(request, "users/login.html", ret)
        else:
            msg = "用户名和密码不能够为空！"
            ret = {"msg": msg, "login_form": login_form}
            return render(request, "users/login.html", ret)


class LogoutView(View):
    """
    用户登出,直接调用django内部方法
    """
    def get(self, request):
        # 登出用户
        logout(request)
        # 根据url名称进行反向解析
        return HttpResponseRedirect(reverse("login"))


class UserView(LoginRequiredMixin, View):
    """
    用户管理，跳转到管理员信息列表
    """
    def get(self, request):
        return render(request, 'users/user-list.html')


class UserListView(LoginRequiredMixin, View):
    """
    获取用户列表信息
    包括，编号、名称、手机、邮件、路径、以及当前用户的状态
    """
    def get(self, request):
        fields = ['id', 'name', 'mobile', 'email', 'url', 'is_active']
        filters = dict()
        if 'select' in request.GET and request.GET.get('select'):
            filters['is_active'] = request.GET.get('select').exclude(username='cheertt')
        ret = dict(data=list(User.objects.filter(**filters).values(*fields)))
        return HttpResponse(json.dumps(ret, cls=DjangoJSONEncoder), content_type='application/json')


class UserCreateView(LoginRequiredMixin, View):
    """
    添加用户，管理员添加商户信息
    """
    def get(self, request):
        users = User.objects.exclude(username='admin')

        ret = {
            'users': users,
        }
        return render(request, 'users/user_create.html', ret)

    def post(self, request):
        user_create_form = UserCreateForm(request.POST)
        if user_create_form.is_valid():
            new_user = user_create_form.save(commit=False)
            new_user.password = make_password(user_create_form.cleaned_data['password'])
            new_user.save()
            user_create_form.save_m2m()
            ret = {'status': 'success'}
        else:
            pattern = '<li>.*?<ul class=.*?><li>(.*?)</li>'
            errors = str(user_create_form.errors)
            user_create_form_errors = re.findall(pattern, errors)
            ret = {
                'status': 'fail',
                'user_create_form_errors': user_create_form_errors[0]
            }
        return HttpResponse(json.dumps(ret), content_type='application/json')


class UserEnableView(LoginRequiredMixin, View):
    """
    启用用户：单个或批量启用
    """
    def post(self, request):
        if 'id' in request.POST and request.POST['id']:
            id_nums = request.POST.get('id')
            queryset = User.objects.extra(where=["id IN(" + id_nums + ")"])
            queryset.filter(is_active=False).update(is_active=True)
            ret = {'result': 'True'}
        return HttpResponse(json.dumps(ret), content_type='application/json')


class UserDisableView(LoginRequiredMixin, View):
    """
    启用用户：单个或批量启用
    """
    def post(self, request):
        if 'id' in request.POST and request.POST['id']:
            id_nums = request.POST.get('id')
            queryset = User.objects.extra(where=["id IN(" + id_nums + ")"])
            queryset.filter(is_active=True).update(is_active=False)
            ret = {'result': 'True'}
        return HttpResponse(json.dumps(ret), content_type='application/json')


class UserDeleteView(LoginRequiredMixin, View):
    """
    删除数据：支持删除单条记录和批量删除
    """
    def post(self, request):
        id_nums = request.POST.get('id')
        User.objects.extra(where=["id IN (" + id_nums + ")"]).delete()
        ret = {
            'result': 'true',
            'message': '数据删除成功！'
        }
        return HttpResponse(json.dumps(ret), content_type='application/json')

templates/users/user-list.html
{% extends "base-left.html" %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.min.css' %}">
<link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
<!-- iCheck for checkboxes and radio inputs -->
{% endblock %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header margin-bottom">
  <ol class="breadcrumb">
    <li><a href=""><i class="fa fa-dashboard"></i>办公平台</a></li>
    <li class="active"><a href="{% url 'users:user' %}">系统</a></li>
    <li class="active"><a href="">用户管理</a></li>
  </ol>
</section>
    <!-- Main content -->
  <section class="content">
     <div id="devlist">
        <div class="box box-primary" id="liebiao">
            <div class="box-header">
                <div class="btn-group pull-left">
                    <button type="button" id="btnRefresh" class="btn btn-default">
                        <i class="glyphicon glyphicon-repeat"></i>刷新
                    </button>
                </div>
                <div class="btn-group pull-left">&nbsp</div>
                <div class="btn-group pull-left">
                    <button type="button" id="btnCreate" class="btn btn-default">
                        <i class="glyphicon glyphicon-plus"></i>新增
                    </button>
                </div>
                <div class="btn-group pull-left">&nbsp</div>
                <div class="btn-group pull-left">
                    <button type="button" id="btnDelete" class="btn btn-default">
                        <i class="glyphicon glyphicon-trash"></i>删除
                    </button>
                </div>
                <div class="btn-group pull-left">&nbsp</div>
                <div class="btn-group pull-left">
                    <button type="button" id="btnEnable" class="btn btn-default">
                        <i class="glyphicon glyphicon-ok-circle"></i>启用
                    </button>
                    <button type="button" id="btnDisable" class="btn btn-default">
                        <i class="glyphicon glyphicon-ban-circle"></i>禁用
                    </button>
                </div>
                <div class="btn-group pull-right">
                    <form class="form-inline">
                        <div class="form-group">
                            <label>用户状态：</label>
                            <select id="select" name="select" class="form-control">
                                <option style='text-align:center' value=''>-----所有-----</option>
                                <option value="True">启用</option>
                                <option value="False">禁用</option>
                            </select>
                        </div>
                    </form>
                </div>
            </div>
            <div class="box-body">
                <table id="dtbList" class="display" cellspacing="0" width="100%">
                    <thead>
                    <tr valign="middle">
                        <th><input type="checkbox" id="checkAll"></th>
                        <th>ID</th>
                        <th>姓名</th>
                        <th>手机</th>
                        <th>邮箱</th>
                        <th>url</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <br> <br>
            </div>
        </div>
     </div>
  </section>

    <!-- /.content -->

{% endblock %}

{% block javascripts %}
  <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'plugins/datatables/dataTables.const.js' %}"></script>
  <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
  <!-- iCheck 1.0.1 -->
  <script type="text/javascript">
	$(function() {
	    $('#SYSTEM-BASIC').addClass('active');
		$('#SYSTEM-BASIC-USER').addClass('active');

	});
  </script>

    <script type="text/javascript">
var oDataTable=null;
$(function() {
	oDataTable = initTable();
	function initTable() {
		var oTable=$('#dtbList').DataTable($.extend(true,{},
						DATATABLES_CONSTANT.DATA_TABLES.DEFAULT_OPTION,
						{
							ajax : {
								"url":"{% url 'users:user-list' %}",
								"data":function ( d ) {
									d.select=$("#select").val();
								}
						},
						columns : [
								DATATABLES_CONSTANT.DATA_TABLES.COLUMN.CHECKBOX,
								{
									data : "id",
									width : "5%",
								},
								{
									data : "name",//parent
									width : "10%",
								},
								{
									data : "mobile",
								},
								{
									data : "email",
								},
                                {
                                    data : "url",
								},
                                {
                                    data : "is_active",
                                    render : function(data) {
										if (data==true){
											return "启用";
										}else{
											return "禁用";
										}
									}
								},
								{
									data : "id",
									width : "12%",
									bSortable : "false",
									render : function(data, type, row, meta) {
										var ret="";
										var ret="<button name='btnConfig' title='删除' onclick='doDelete("
                                            + data + ")'><i class='glyphicon glyphicon-trash'></i></button>";
										return ret;
									}
								} ],
						"order":[
                    [2, 'desc']
		 	           ],
						}));
		return oTable;
	}

	//checkbox全选
    $("#checkAll").on("click", function () {
        if ($(this).prop("checked") === true) {
            $("input[name='checkList']").prop("checked", $(this).prop("checked"));
            $('#example tbody tr').addClass('selected');
        } else {
            $("input[name='checkList']").prop("checked", false);
            $('#example tbody tr').removeClass('selected');
        }
    });


	$("#btnCreate").click(function() {
		var div=layer.open({
			type : 2,
			title : '新增',
			shadeClose : false,
			maxmin : true,
            area : [ '800px', '720px' ],
			content : '/users/user/create',
			end : function() {
				//关闭时做的事情
				oDataTable.ajax.reload();
			}
		});
		layer.full(div)
	});

	$("#btnRefresh").click(function(){
		oDataTable.ajax.reload();
	});

	//批量删除
	$("#btnDelete").click(function() {
		if ($("input[name='checkList']:checked").length == 0){
			layer.msg("请选择要删除的记录");
			return ;
		}

		var arrId= new Array();
		$("input[name='checkList']:checked").each(function(){
			//alert($(this).val());
			arrId.push($(this).val());
		});

		sId=arrId.join(',');

		layer.alert('确定删除吗？', {
			title:'提示'
			,icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
			,time: 0 //不自动关闭
			,btn: ['YES', 'NO']
			,yes: function(index){
			 	layer.close(index);
			 	$.ajax({
					type: "POST",
					url : "{% url "users:user-delete" %}",
					data : {"id":sId, csrfmiddlewaretoken: '{{ csrf_token }}'},
					cache: false,
					success : function(msg) {
						if (msg.result){
							layer.alert("操作成功");
							oDataTable.ajax.reload();
						}else{
							//alert(msg.message);
							layer.alert("操作失败");
						}
						return ;
					}
				});
			}
		});
	});


	//批量启用
	$("#btnEnable").click(function() {
		if ($("input[name='checkList']:checked").length == 0){
			layer.msg("请选择要启用的用户");
			return ;
		}

		var arrId= new Array();
		$("input[name='checkList']:checked").each(function(){
			//alert($(this).val());
			arrId.push($(this).val());
		});

		sId=arrId.join(',');

		layer.alert('确定启用吗？', {
			title:'提示'
			,icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
			,time: 0 //不自动关闭
			,btn: ['YES', 'NO']
			,yes: function(index){
			 	layer.close(index);
			 	$.ajax({
					type: "POST",
					url : "{% url "users:user-enable" %}",
					data : {"id":sId, csrfmiddlewaretoken: '{{ csrf_token }}'},
					cache: false,
					success : function(msg) {
						if (msg.result){
							layer.alert("启用用户成功", {icon: 1});
							oDataTable.ajax.reload();
						}else{
							//alert(msg.message);
							layer.alert("启用用户失败", {icon: 5});
						}
						return ;
					}
				});
			}
		});
	});

	//批量禁用
	$("#btnDisable").click(function() {
		if ($("input[name='checkList']:checked").length == 0){
			layer.msg("请选择要禁用的用户");
			return ;
		}

		var arrId= new Array();
		$("input[name='checkList']:checked").each(function(){
			//alert($(this).val());
			arrId.push($(this).val());
		});

		sId=arrId.join(',');

		layer.alert('确定禁用吗？', {
			title:'提示'
			,icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
			,time: 0 //不自动关闭
			,btn: ['YES', 'NO']
			,yes: function(index){
			 	layer.close(index);
			 	$.ajax({
					type: "POST",
					url : "{% url "users:user-disable" %}",
					data : {"id":sId, csrfmiddlewaretoken: '{{ csrf_token }}'},
					cache: false,
					success : function(msg) {
						if (msg.result){
							layer.alert("禁用用户成功", {icon: 1});
							oDataTable.ajax.reload();
						}else{
							//alert(msg.message);
							layer.alert("禁用用户失败", {icon: 5});
						}
						return ;
					}
				});
			}
		});
	});

	$("#select").change(function(){
		//alert($("#select").val())
		oDataTable.ajax.reload();
	});


});

// 跳转到用户详情页面
function doUpdate(id){
	var div=layer.open({
		type : 2,
		title : '编辑',
		shadeClose : false,
    	maxmin : true,
		area : [ '800px', '650px' ],
		content : [],
		end : function() {
			oDataTable.ajax.reload();
		}
	});
    layer.full(div)
}

// 跳转到用户密码修改
function doChangepasswd(id){
	layer.open({
		type : 2,
		title : '编辑',
		shadeClose : false,
    	maxmin : true,
		area : [ '850px', '600px' ],
		content : [ ],
		end : function() {
			oDataTable.ajax.reload();
		}
	});
}

//删除单个用户
function doDelete(id){
    layer.alert('确定删除吗？', {
        title:'提示'
        ,icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
        ,time: 0 //不自动关闭
        ,btn: ['YES', 'NO']
        ,yes: function(index){
            layer.close(index);
            $.ajax({
                type: "POST",
                url : "{% url "users:user-delete" %}",
                data : {"id":id, csrfmiddlewaretoken: '{{ csrf_token }}'},  //防止post数据时报 csrf_token 403
                cache: false,
                success : function(msg) {
                    if (msg.result){
                        layer.alert(msg.message,{icon: 1});
                        oDataTable.ajax.reload();
                    }else{
                        //alert(msg.message);
                        layer.alert('删除失败', {icon: 5});
                    }
                    return ;
                }
            });
        }
    });

}

</script>
{% endblock %}